global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "snmp"
    static_configs:
      - targets:
          - "snmp-device:161"
    metrics_path: /snmp
    params:
      module: [default]
    relabel_configs:
      - source_labels: [_address_]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: _address_
        replacement: snmp-exporter:9116